services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: shopifyzz/client-prod
    container_name: shopifyzz/client-prod
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    restart: unless-stopped
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: shopifyzz/server-prod
    container_name: shopifyzz/server-prod
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env
    restart: unless-stopped
