services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: shopifyzz/client-dev
    container_name: shopifyzz-client-dev
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: shopifyzz/server-dev
    container_name: shopifyzz-server-dev
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: unless-stopped
